<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\awoken.png" />
    <None Remove="Images\CARDFRAME2.png" />
    <None Remove="Images\dragon-totem.png" />
    <None Remove="Images\filter.png" />
    <None Remove="Images\square-x.png" />
    <None Remove="Images\type.png" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_001.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_002.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_003.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_004.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_005.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_006.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_007.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_008.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_009.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_010.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_011.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_012.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_013.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_014.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_015.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_016.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_017.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_018.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_019.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_020.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_021.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_022.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_023.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_024.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_025.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_026.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_027.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_028.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_029.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_030.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_031.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_032.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_033.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_034.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_035.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_036.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_037.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_038.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_039.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_040.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_041.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_042.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_043.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_044.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_045.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_046.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_047.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_048.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_049.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_050.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_051.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_052.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_053.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_054.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_055.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_056.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_057.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_058.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_059.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_060.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_061.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_062.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_063.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_064.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_065.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_066.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_067.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_068.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_069.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_070.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_071.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_072.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_073.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_074.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_075.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_076.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_077.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_078.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_079.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_080.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_081.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_082.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_083.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_084.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_085.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_086.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_087.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_088.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_089.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_090.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_091.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_092.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_093.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_094.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_095.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_096.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_097.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_098.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_099.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_100.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_101.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_102.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_103.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_104.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_105.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_106.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_107.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_108.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_109.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_110.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_111.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_112.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_113.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_114.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_115.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_116.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_117.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_118.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_119.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_120.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_121.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_122.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_123.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_124.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_125.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_126.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_127.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_128.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_129.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_130.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_131.PNG" />
    <None Remove="PADDashFormation\images\cards_en\CARDS_132.PNG" />
    <None Remove="PADDashFormation\monsters-info\mon_en.json" />
    <None Remove="PADDashFormation\monsters-info\skill_en.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\awoken.png" />
    <EmbeddedResource Include="Images\CARDFRAME2.png" />
    <EmbeddedResource Include="Images\dragon-totem.png" />
    <EmbeddedResource Include="Images\filter.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\square-x.png" />
    <EmbeddedResource Include="Images\type.png" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_001.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_002.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_003.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_004.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_005.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_006.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_007.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_008.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_009.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_010.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_011.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_012.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_013.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_014.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_015.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_016.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_017.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_018.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_019.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_020.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_021.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_022.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_023.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_024.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_025.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_026.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_027.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_028.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_029.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_030.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_031.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_032.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_033.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_034.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_035.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_036.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_037.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_038.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_039.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_040.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_041.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_042.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_043.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_044.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_045.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_046.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_047.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_048.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_049.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_050.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_051.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_052.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_053.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_054.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_055.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_056.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_057.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_058.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_059.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_060.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_061.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_062.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_063.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_064.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_065.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_066.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_067.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_068.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_069.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_070.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_071.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_072.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_073.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_074.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_075.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_076.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_077.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_078.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_079.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_080.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_081.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_082.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_083.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_084.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_085.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_086.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_087.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_088.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_089.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_090.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_091.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_092.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_093.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_094.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_095.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_096.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_097.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_098.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_099.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_100.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_101.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_102.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_103.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_104.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_105.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_106.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_107.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_108.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_109.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_110.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_111.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_112.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_113.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_114.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_115.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_116.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_117.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_118.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_119.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_120.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_121.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_122.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_123.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_124.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_125.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_126.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_127.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_128.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_129.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_130.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_131.PNG" />
    <EmbeddedResource Include="PADDashFormation\images\cards_en\CARDS_132.PNG" />
    <EmbeddedResource Include="PADDashFormation\monsters-info\mon_en.json" />
    <EmbeddedResource Include="PADDashFormation\monsters-info\skill_en.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
    <PackageReference Include="Xamarin.FFImageLoading" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2196" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
  </ItemGroup>
</Project>
