<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\mon_en.json" />
    <None Remove="Data\skill_en.json" />
    <None Remove="Images\awoken.png" />
    <None Remove="Images\CARDFRAME2.png" />
    <None Remove="Images\CARDS_001.PNG" />
    <None Remove="Images\CARDS_002.PNG" />
    <None Remove="Images\CARDS_003.PNG" />
    <None Remove="Images\CARDS_004.PNG" />
    <None Remove="Images\CARDS_005.PNG" />
    <None Remove="Images\CARDS_006.PNG" />
    <None Remove="Images\CARDS_007.PNG" />
    <None Remove="Images\CARDS_008.PNG" />
    <None Remove="Images\CARDS_009.PNG" />
    <None Remove="Images\CARDS_010.PNG" />
    <None Remove="Images\CARDS_011.PNG" />
    <None Remove="Images\dragon-totem.png" />
    <None Remove="Images\type.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\mon_en.json" />
    <EmbeddedResource Include="Data\skill_en.json" />
    <EmbeddedResource Include="Images\awoken.png" />
    <EmbeddedResource Include="Images\CARDFRAME2.png" />
    <EmbeddedResource Include="Images\CARDS_001.PNG" />
    <EmbeddedResource Include="Images\CARDS_002.PNG" />
    <EmbeddedResource Include="Images\CARDS_003.PNG" />
    <EmbeddedResource Include="Images\CARDS_004.PNG" />
    <EmbeddedResource Include="Images\CARDS_005.PNG" />
    <EmbeddedResource Include="Images\CARDS_006.PNG" />
    <EmbeddedResource Include="Images\CARDS_007.PNG" />
    <EmbeddedResource Include="Images\CARDS_008.PNG" />
    <EmbeddedResource Include="Images\CARDS_009.PNG" />
    <EmbeddedResource Include="Images\CARDS_010.PNG" />
    <EmbeddedResource Include="Images\CARDS_011.PNG" />
    <EmbeddedResource Include="Images\dragon-totem.png" />
    <EmbeddedResource Include="Images\type.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
    <PackageReference Include="Xamarin.FFImageLoading" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2196" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
  </ItemGroup>
</Project>